### PR TITLE
added tcl script to be run in windows

### PR DESCRIPTION
**Pull request by overcookedlobster**
added gitignore for vivado's generated log files + simple readme on how to use the scripts

to do: add a script folder, but for now in the main folder

### CODE REVIEW

**Comment by zeroleaked** [comment]
Tried running the tcl on vivado linux. What is this?

```
source /home/zir/os/i2c/oti-i2c-bridge/run_axil.tcl
# set BUILD_DIR "build"
# file mkdir $BUILD_DIR
# file delete -force {*}[glob -nocomplain $BUILD_DIR/xsim.dir]
wrong # args: should be "file delete ?options? file ?file ...?"
    while executing
"file delete -force {*}[glob -nocomplain $BUILD_DIR/xsim.dir]"
    (file "/home/zir/os/i2c/oti-i2c-bridge/run_axil.tcl" line 4)

**Comment by overcookedlobster** [comment]
> Tried running the tcl on vivado linux. What is this?
> 
> ```
> source /home/zir/os/i2c/oti-i2c-bridge/run_axil.tcl
> # set BUILD_DIR "build"
> # file mkdir $BUILD_DIR
> # file delete -force {*}[glob -nocomplain $BUILD_DIR/xsim.dir]
> wrong # args: should be "file delete ?options? file ?file ...?"
>     while executing
> "file delete -force {*}[glob -nocomplain $BUILD_DIR/xsim.dir]"
>     (file "/home/zir/os/i2c/oti-i2c-bridge/run_axil.tcl" line 4)
> ```

try using vivado -mode tcl -source run_axil.tcl

**Comment by zeroleaked** [comment]
bikin folder aja mo, bentar lagi aku juga mau pr project_init

**Review by zeroleaked — APPROVED** [review]
No errors, good log, oke oce

**Pull request merged**
